//
//  RTSSDBModel.m
//  RTSS
//
//  Created by shengyp on 14/11/20.
//  Copyright (c) 2014年 shengyp. All rights reserved.
//

#import "RTSSDBModel.h"

@implementation RTSSDBModel

+ (NSString*)createConfigTableSql{
    NSString* format = @"CREATE TABLE "CONFIG_TABLE_NAME@" (%@ INTEGER DEFAULT 10)";
    return [NSString stringWithFormat:format, CONFIG_VERSION_COLUMN];
}

+ (NSString*)createFriendsTableSql{
    NSString* format = @"CREATE TABLE "FRIENDS_TABLE_NAME@" (%@ INTEGER PRIMARY KEY AUTOINCREMENT, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ INTEGER, UNIQUE (%@,%@))";
    return [NSString stringWithFormat:format, FRIENDS_SN_COLUMN, FRIENDS_MYID_COLUMN, FRIENDS_ID_COLUMN, FRIENDS_NAME_COLUMN, FRIENDS_PHONENUMBER_COLUMN, FRIENDS_PORTRAIT_COLUMN, FRIENDS_TIMESTAMP_COLUMN, FRIENDS_MYID_COLUMN, FRIENDS_PHONENUMBER_COLUMN];
}

+ (NSString*)createEventTableSql{
    NSString* format = @"CREATE TABLE "EVENT_TABLE_NAME@" (%@ INTEGER PRIMARY KEY AUTOINCREMENT, %@ NVARCHAR, %@ INTEGER, %@ NVARCHAR, %@ NVARCHAR, %@ BLOB, %@ INTEGER)";
    return [NSString stringWithFormat:format, EVENT_ID_COLUMN, EVENT_MYID_COLUMN, EVENT_TYPE_COLUMN, EVENT_PEER_PHONENUMBER_COLUMN, EVENT_DESC_COLUMN, EVENT_PARAMETERS_COLUMN, EVENT_TIMESTAMP_COLUMN];
}

+ (NSString*)createMessageTableSql{
    NSString* format = @"CREATE TABLE "MESSAGE_TABLE_NAME@" (%@ NVARCHAR PRIMARY KEY, %@ INTEGER, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ DOUBLE, %@ NVARCHAR, %@ INTEGER)";
    return [NSString stringWithFormat:format, MESSAGE_ID_COLUMN, MESSAGE_TYPE_COLUMN, MESSAGE_FROMCODE_COLUMN, MESSAGE_FROMNAME_COLUMN, MESSAGE_TITLE_COLUMN, MESSAGE_CONTENT_COLUMN, MESSAGE_TIMESTAMP_COLUMN, MESSAGE_HREF_COLUMN, MESSAGE_READ_COLUMN];
}

+ (NSString*)createFindTableSql {
    NSString *format = @"CREATE TABLE "FIND_TABLE_NAME@" (%@ INTEGER PRIMARY KEY AUTOINCREMENT, %@ INTEGER UNIQUE, %@ INTEGER, %@ INTEGER, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ INTEGER, %@ INTEGER, %@ INTEGER, %@ NVARCHAR, %@ INTEGER)";
    return [NSString stringWithFormat:format,FIND_COLUMS_SN,FIND_COLUMS_ID,FIND_COLUMS_TYPE,FIND_COLUMS_CATALOG,FIND_COLUMS_NAME,FIND_COLUMS_TITLE,FIND_COLUMS_DATE,FIND_COLUMS_ICON_URL,FIND_COLUMS_PIC_URL,FIND_COLUMS_DESCRIPTION,FIND_COLUMS_TARGET_URL,FIND_COLUMS_HOT_COUNT,FIND_COLUMS_HAS_HOT,FIND_COLUMS_COMMENT_COUNT,FIND_COLUMS_TAG_INFO,FIND_COLUMS_HAS_COLLECT];
}

+ (NSString *)createCollectionSql {
    NSString *format = @"CREATE TABLE "COLLECTION_TABLE_NAME@" (%@ INTEGER PRIMARY KEY, %@ INTEGER, %@ INTEGER, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ NVARCHAR, %@ INTEGER, %@ INTEGER, %@ INTEGER, %@ NVARCHAR, %@ INTEGER)";
    return [NSString stringWithFormat:format,FIND_COLUMS_ID,FIND_COLUMS_TYPE,FIND_COLUMS_CATALOG,FIND_COLUMS_NAME,FIND_COLUMS_TITLE,FIND_COLUMS_DATE,FIND_COLUMS_ICON_URL,FIND_COLUMS_PIC_URL,FIND_COLUMS_DESCRIPTION,FIND_COLUMS_TARGET_URL,FIND_COLUMS_HOT_COUNT,FIND_COLUMS_HAS_HOT,FIND_COLUMS_COMMENT_COUNT,FIND_COLUMS_TAG_INFO,FIND_COLUMS_HAS_COLLECT];
}

@end
